name: pr_number → cloud run-compatible tag

inputs:
  pr_number:
    description: "Convert the format '<pr_number>/merge' to a CloudRun-compatible tag.(e.g. 123/merge -> pr123)"
    required: true

outputs:
  cloudrun_compatible_tag:
    description: "The pull request number converted to a Cloud Run-compatible tag."
    value: ${{ steps.transform-string.outputs.cloudrun-compatible-tag }}

runs:
  using: composite
  steps:
    # Resource name must use only lowercase letters, numbers and '-'.
    # Must begin with a letter and cannot end with a '-'.
    # Maximum length is 63 characters.
    - name: Transform string
      id: transform-string
      run: echo "cloudrun-compatible-tag=pr$(echo ${{ inputs.pr_number }} | sed 's|/merge||')" >> $GITHUB_OUTPUT
      shell: bash
